server:
  port: 8081
  servlet:
    context-path: /satander-bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/postgres
    username: santander-bootcamp-db
    password: santander-bootcamp-db
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto bootcamp DIO - Santander